# Locally override default configurations
#
# This file overrides configurations set in `config/config.defaults.yml`.
# Keep in mind that environment variables override setting in this file.
#
# Usage:
#
# Copy this file from `config/config.example.yml` to `config/config.yml`
#
domain: "padall-core.herokuapp.com"

development:
  secret_key_base: 37f0382f5c697f4fc756cdefb2409473796d166140f2b8ca7783c9917a7630e79e8c3a3bc03dba84a1ecbd4bebfcb11dcce301e6a770174966cdbc22939afe0a
  always_use_ssl: false
  # Skip email confirmation
  skip_email_confirmation: true
  log_level: DEBUG
  smtp_email_address: "in-v3.mailjet.com"
  smtp_email_port: 587
  smtp_email_user_name: "4ddb6b64c7668bc8a05e4cc4a6a97537"
  smtp_email_password: "a1259805fca7b79a1ba1a8418b3435de"
  smtp_email_domain: "localhost"
  sharetribe_mail_from_address: "no-reply@padall.co.uk"



test:
  secret_key_base: 37f0382f5c697f4fc756cdefb2409473796d166140f2b8ca7783c9917a7630e79e8c3a3bc03dba84a1ecbd4bebfcb11dcce301e6a770174966cdbc22939afe0a
  always_use_ssl: false
  # Skip email confirmation
  skip_email_confirmation: true
  log_level: DEBUG
  smtp_email_address: "in-v3.mailjet.com"
  smtp_email_port: 587
  smtp_email_user_name: "4ddb6b64c7668bc8a05e4cc4a6a97537"
  smtp_email_password: "a1259805fca7b79a1ba1a8418b3435de"
  smtp_email_domain: "localhost"
  sharetribe_mail_from_address: "no-reply@padall.co.uk"

 

staging:
  secret_key_base: 37f0382f5c697f4fc756cdefb2409473796d166140f2b8ca7783c9917a7630e79e8c3a3bc03dba84a1ecbd4bebfcb11dcce301e6a770174966cdbc22939afe0a
  always_use_ssl: false

  # Skip email confirmation
  skip_email_confirmation: true
  log_level: INFO
  smtp_email_address: "in-v3.mailjet.com"
  smtp_email_port: 587
  smtp_email_user_name: "4ddb6b64c7668bc8a05e4cc4a6a97537"
  smtp_email_password: "a1259805fca7b79a1ba1a8418b3435de"
  smtp_email_domain: "padall.co.uk"
  sharetribe_mail_from_address: "no-reply@padall.co.uk"

production:
  secret_key_base: 37f0382f5c697f4fc756cdefb2409473796d166140f2b8ca7783c9917a7630e79e8c3a3bc03dba84a1ecbd4bebfcb11dcce301e6a770174966cdbc22939afe0a
  always_use_ssl: false
  
  # Skip email confirmation
  skip_email_confirmation: true
  log_level: DEBUG
  smtp_email_address: "in-v3.mailjet.com"
  smtp_email_port: 587
  smtp_email_user_name: "4ddb6b64c7668bc8a05e4cc4a6a97537"
  smtp_email_password: "a1259805fca7b79a1ba1a8418b3435de"
  smtp_email_domain: "padall.co.uk"
  sharetribe_mail_from_address: "no-reply@padall.co.uk"

